# .github/workflows/release-please.yml
name: release-please
on:
  push:
    branches:
      - trunk
jobs:
  release-please:
    runs-on: ubuntu-latest
    id: release
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          default-branch: trunk
      - uses: actions/checkout@v4
        if: ${{ steps.release.outputs.releases_created }}
      - name: Install dependencies
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          pip install -r requirements-dev.txt
      - name: Build App
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          pyinstaller --onefile todo.py
          python -m build .
      - name: Upload build artifacts
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} dist/todo
          gh release upload ${{ steps.release.outputs.tag_name }} dist/*.whl
          gh release upload ${{ steps.release.outputs.tag_name }} dist/*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
