name: Todo CLI Pipeline

on:
  pull_request:
    branches: [dev, int, release]
  push:
    branches: [release]

permissions:
  contents: read

jobs:
  All-Ubuntu-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Testing
        run: |
          pipenv run pytest -q src/testing/unit/
      - name: Lint
        run: |
          pipenv run pylint $(git ls-files '*.py')
      - name: Security Check
        run: |
          pipenv check
