name: Todo CLI Pipeline

on:
  pull_request:
    branches: [trunk]
  push:
    branches: [trunk]

permissions:
  contents: read

jobs:
  All-Ubuntu-Checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Setup
        run: |
          pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Testing
        run: |
          pipenv run pytest -q tests/
      - name: Lint
        run: |
          pipenv run pylint todo_cli/
          echo "Linting Tests..."
          pipenv run pylint tests/
      - name: Build
        run: |
          pyinstaller --onefile todo.py
